import { StyleSheet } from 'react-native';
import { Spacing } from '@/constants/theme';

export const createHomeStyles = (theme: any) => StyleSheet.create({
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
    gap: Spacing.two,
    zIndex: 10,
  },
  searchBarWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    height: 42,
    borderRadius: Spacing.two,
    paddingHorizontal: Spacing.two,
    borderWidth: 1,
    borderColor: 'transparent',
    // Subtle neon shadow/glow
    shadowColor: theme.accent,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 1,
  },
  searchBarInput: {
    flex: 1,
    height: '100%',
    marginLeft: Spacing.one,
    fontSize: 14,
  },
  clearSearchInputBtn: {
    padding: Spacing.one,
  },
  dropdownContainer: {
    position: 'relative',
  },
  dropdownTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 42,
    paddingHorizontal: Spacing.three,
    borderRadius: Spacing.two,
    justifyContent: 'center',
    maxWidth: 140,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  dropdownLabel: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  dropdownMenu: {
    position: 'absolute',
    top: 48,
    right: 0,
    width: 160,
    borderRadius: Spacing.two,
    borderWidth: 1,
    borderColor: theme.backgroundSelected,
    paddingVertical: Spacing.one,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 8,
    zIndex: 99,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.two,
    paddingHorizontal: Spacing.three,
    gap: Spacing.one,
  },
  dropdownItemText: {
    fontSize: 12,
  },
  contentCanvas: {
    flex: 1,
    paddingHorizontal: Spacing.three,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Spacing.two,
    marginBottom: Spacing.three,
    borderBottomWidth: 1,
    paddingBottom: Spacing.two,
  },
  headerMarker: {
    width: 6,
    height: 20,
    marginRight: 10,
    borderRadius: 3,
    // Glowing neon badge
    shadowColor: theme.accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 6,
    elevation: 4,
  },
  gridHeaderTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  mangaCard: {
    flexDirection: 'row',
    borderRadius: Spacing.three,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 3,
    marginBottom: Spacing.three,
    padding: Spacing.two,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.03)',
  },
  mangaCardImage: {
    width: 90,
    height: 125,
    borderRadius: Spacing.two,
  },
  mangaCardInfo: {
    flex: 1,
    marginLeft: Spacing.three,
    justifyContent: 'space-between',
    paddingVertical: Spacing.half,
  },
  mangaCardTitle: {
    fontSize: 14,
    lineHeight: 18,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Spacing.one,
    marginBottom: Spacing.one,
  },
  starIcon: {
    marginRight: 2,
  },
  ratingText: {
    marginLeft: Spacing.two,
    fontSize: 12,
  },
  chaptersList: {
    marginTop: Spacing.one,
    gap: Spacing.one,
  },
  chapterRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  chapterPill: {
    borderRadius: 6,
    paddingHorizontal: Spacing.two,
    paddingVertical: 3,
    alignSelf: 'flex-start',
    borderWidth: 0.5,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  chapterPillText: {
    fontSize: 11,
  },
  chapterDate: {
    marginLeft: Spacing.two,
    fontSize: 11,
  },
  emptyGridState: {
    paddingTop: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
