import { StyleSheet } from 'react-native';
import { Spacing, MaxContentWidth } from '@/constants/theme';

export const createLibraryStyles = (theme: any) => StyleSheet.create({
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.three,
    gap: Spacing.four,
    maxWidth: MaxContentWidth,
    alignSelf: 'center',
    width: '100%',
  },
  header: {
    paddingVertical: Spacing.two,
    gap: Spacing.half,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
  },
  sectionContainer: {
    gap: Spacing.two,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.one,
    paddingHorizontal: Spacing.one,
  },
  sectionTitle: {
    fontSize: 13,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  historyCard: {
    flexDirection: 'row',
    padding: Spacing.two,
    borderRadius: Spacing.two,
    gap: Spacing.two,
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: 'rgba(255, 255, 255, 0.03)',
  },
  historyImage: {
    width: 48,
    height: 68,
    borderRadius: 4,
    backgroundColor: '#333',
    borderWidth: 0.5,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  historyInfo: {
    flex: 1,
    gap: 2,
  },
  historyMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  historyPath: {
    fontSize: 10,
    flex: 1,
  },
  historyFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  historyReadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: Spacing.one,
    borderWidth: 1,
    gap: Spacing.one,
    // Glow effect
    shadowColor: theme.accent,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 2,
  },
  historyReadBtnText: {
    fontSize: 12,
  },
  emptyState: {
    padding: Spacing.five,
    borderRadius: Spacing.three,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.03)',
  },
  emptySubtitle: {
    textAlign: 'center',
    fontSize: 12,
    marginTop: Spacing.one,
    maxWidth: 280,
  },
  clearBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.two,
    borderRadius: Spacing.two,
    borderWidth: 1,
    gap: Spacing.two,
    marginTop: Spacing.two,
  },
  clearBtnText: {
    color: '#f44336',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(5, 2, 10, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.four,
  },
  confirmModalBox: {
    width: '90%',
    maxWidth: 320,
    borderRadius: Spacing.three,
    padding: Spacing.four,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(244, 67, 54, 0.4)',
    shadowColor: '#f44336',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 5,
  },
  successModalBox: {
    width: '90%',
    maxWidth: 320,
    borderRadius: Spacing.three,
    padding: Spacing.four,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(208, 38, 255, 0.4)',
    shadowColor: theme.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 5,
  },
  confirmModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: Spacing.two,
    marginBottom: Spacing.one,
    textAlign: 'center',
  },
  confirmModalText: {
    fontSize: 13,
    textAlign: 'center',
    marginBottom: Spacing.three,
    lineHeight: 18,
  },
  confirmModalButtons: {
    flexDirection: 'row',
    gap: Spacing.two,
    width: '100%',
  },
  confirmModalBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: Spacing.one,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelBtn: {
    borderColor: theme.backgroundSelected,
    backgroundColor: theme.backgroundSelected,
  },
  deleteConfirmBtn: {
    borderColor: '#f44336',
    backgroundColor: '#f44336',
  },
  successModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.accent,
    marginTop: Spacing.two,
    marginBottom: Spacing.one,
    textAlign: 'center',
    textShadowColor: theme.accent,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  successModalText: {
    fontSize: 13,
    textAlign: 'center',
    marginBottom: Spacing.three,
    lineHeight: 18,
  },
  successCloseBtn: {
    width: '100%',
    paddingVertical: 10,
    borderRadius: Spacing.one,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: theme.accent,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 3,
  },
  // Search bar shared between downloads history and library
  searchBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: Spacing.two,
    paddingHorizontal: Spacing.two,
    height: 40,
    borderWidth: 0.5,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    gap: Spacing.one,
  },
  searchBarInput: {
    flex: 1,
    height: '100%',
    fontSize: 13,
  },
  // Scrollable history container
  historyScrollContainer: {
    maxHeight: 400,
    overflow: 'hidden',
  },
});
